project:
  type: website
  output-dir: docs

website:
  title: "GCP by HRM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Day1/day1.qmd
        text: Day1

format:
  html:
    theme:
      light: 
        - cosmo
      dark:
        - sketchy
    css: styles.css
    toc: true



