project:
  type: website
  output-dir: docs

website:
  title: "GCP by HRM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Day1/day1.qmd
        text: Day1
      - href: Day2/out.qmd
        text: Day2
      - href: Day3/day3.qmd
        text: Day3
      - href: Day4/day4.qmd
        text: Day4

format:
  html:
    theme:
      light: 
        - cosmo
      dark:
        - sketchy
    css: styles.css
    toc: true



